### ISSUE TITLE
[bug?] 入力待ち状態でCtrl-Cを押すと`^C`が出る

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/minishell#15]
```
bash-3.2$ ./minishell
c?: 0
c-line?: (null)
filepath?: (null)
interactive?: 1
line?: 1
% ^C
% ^C
% ^C
% ^C
% ^C
% 
```

そもそもバグなの？ちなみにBashでは出ない。

**Comment by ryo-manba** [comment]
```
$ ./minishell 
c-line?: (null)
filepath?: (null)
interactive?: 1
% 
% 
% 
% 
```
僕の環境だと改行されるだけですね。
環境依存なんですかね？

**Comment by ryo-manba** [comment]
前に ~/ .inputrcに`set echo-control-characters off` って書いてました。
Make する時に `echo > ~/.inputrc set echo-control-characters off`すれば一応消えますね。

**Comment by ryo-manba** [comment]
`export INPUTRC="設定ファイル"` ってするとそこから読み込んでくれるので、make時にexportさせようと思うんですがどうでしょう？
直に inputrc上書きするの微妙かなと思ったので。

**Comment by ryo-manba** [comment]
ちなみにbashのバージョン5.3くらいだと `^C` 出るので無理に対応する必要もない気がしますが。

**Comment by corvvs** [comment]
> ちなみにbashのバージョン5.3くらいだと ^C 出るので無理に対応する必要もない気がしますが。

であれば問題なさそうですね・・・ありがとうございます。

**Comment by ryo-manba** [comment]
ではそのままにしておきます！
