### ISSUE TITLE
[redirect] cat  << EOF | sleep 3 | cat << EOF のときにsleepが先に実行される

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/minishell#47]
## あるべき状態
```
bash-3.2$ cat  << EOF | sleep 3 | cat << EOF
> EOF
> EOF
bash-3.2$ 
```
heredocの受け取りは親で行う必要がある。
実際につなぎ替えるのは子プロセスで行う。

**Comment by corvvs** [comment]
これ、対応は簡単そうですか？
(個人的にはsleepが先で別にいいような気がします。時間かかるようなら対応しないのもありかなと。)

**Comment by ryo-manba** [comment]
heredocでパイプ挟んだときの挙動がおかしなことになるので、そこだけ修正してみます。

**Comment by ryo-manba** [comment]
これの対応はできたんですが、Ctrl+Cで終了するとプロンプトが2つ出てしまいます。
normもまだなので後で修正します。

**Comment by corvvs** [comment]
単に`cat << EOF`としてenterを押すとherdocを抜ける**ことがある**、という状況になってます。

**Comment by corvvs** [comment]
↑一度Ctrl+Cでheredocを抜けると、次回必ず起きるようです。

**Comment by corvvs** [comment]
↑`g_ex_states`が0でないまま次回に引き継がれるのが原因のようです。

**Comment by corvvs** [comment]
> これの対応はできたんですが、Ctrl+Cで終了するとプロンプトが2つ出てしまいます。

間にsleepがなくても、`cat`の数を増やしても、逆に1つにしても出ますね。

**Comment by ryo-manba** [comment]
もろもろ修正します。
