### ISSUE TITLE
[LPX] bad substitutionのタイミング

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/minishell#6]
## 仮説

```
bash-3.2$ echo hello; ${VAR  }
hello
bash: ${VAR  }: bad substitution
bash-3.2$ 
```

```
bash-3.2$ rm TEST2
rm: TEST2: No such file or directory
bash-3.2$ > TEST2 echo ${VAR  }
bash: ${VAR  }: bad substitution
bash-3.2$ ls TEST2
ls: TEST2: No such file or directory
bash-3.2$ 
```

lexer -> parser -> executor -> コマンドのexpansion -> リダイレクトのexpansion & 処理 -> コマンドの処理
という順番でやってるっぽい。

ちなみに、今は
lexer -> parser -> executor -> リダイレクトのexpansion & 処理 -> コマンドのexpansion -> コマンドの処理

となっているはず。

**Comment by corvvs** [comment]
## 条件を整理する。

- リダイレクトのexpansionのエラーメッセージよりコマンドのexpansionのエラーメッセージの方が先に出る
- リダイレクトのexpansion & 処理を2度やると結果が変わってしまうようなものが存在するので、2度やりたくない
- パイプラインの先頭のコマンド実行前にリダイレクトによりできるファイルはすべて出来ている必要がある。

**Comment by ryo-manba** [comment]
最初にコマンドのエクスパンションするよう修正しときやす。
